[project]
name = "free_crewai_video"
version = "0.1.0"
description = "free-crewai-video using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.14"
dependencies = [
    "crewai-tools>=1.8.1",
    "crewai[anthropic,google-genai,tools]==1.8.1",
    "litellm>=1.75.3",
    "ollama>=0.6.1",
    "python-dotenv>=1.1.1",
]

[project.scripts]
free_crewai_video = "free_crewai_video.main:run"
run_crew = "free_crewai_video.main:run"
train = "free_crewai_video.main:train"
replay = "free_crewai_video.main:replay"
test = "free_crewai_video.main:test"
run_with_trigger = "free_crewai_video.main:run_with_trigger"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"
